# Generated by Django 4.0.1 on 2022-05-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_register_id_alter_register_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='id',
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='email address'),
        ),
    ]
